services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - pg_tracker_data:/var/lib/postgresql/data
      
volumes:
  pg_tracker_data:
  pgadmin_data:
