from __future__ import annotations

from queue import Queue

from sqlmodel import SQLModel

# Global queue that collects all event objects generated by the tracker
event_queue: 'Queue[SQLModel]' = Queue()


def enqueue(event: SQLModel) -> None:
    """Place *event* onto the global :data:`event_queue`."""
    event_queue.put(event)
