# .github/workflows/get_windows_exe.yml
name: Package Application with PyInstaller
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .          # or pip install -r requirements.txt

      - name: Package Application with PyInstaller
        run: |
          pyinstaller --clean pyinstaller.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tracker-exe
          path: dist/tracker/tracker.exe
